---
title: 'Reproducible Research: Peer Assessment 1'
author: "Tina Putnam"
date: "September 05, 2016"
output: html_document

---

## Set Working Directory 
## Loading Data##


activity <- read.csv("activity.csv")


## Clean  data#
head(activity)
##  steps       date interval
##1    NA 2012-10-01        0
##2    NA 2012-10-01        5
##3    NA 2012-10-01       10
##4    NA 2012-10-01       15
##5    NA 2012-10-01       20
##6    NA 2012-10-01       25
names(activity)

## Remove NA's
activity_nona <- activity[complete.cases(activity),]

##What is mean total number of steps taken per day?
##For this part of the assignment, you can ignore the missing values in the dataset.
--1. Calculate the total number of steps taken per day--
total_steps <- aggregate(steps ~ date, activity, sum)
head(total_steps)

##1 2012-10-02   126
##2 2012-10-03 11352
##3 2012-10-04 12116
##4 2012-10-05 13294
##5 2012-10-06 15420
##6 2012-10-07 11015
    
##    Calculate and report the mean and median of the total number of steps taken per day

mean(total_steps$steps)
#[1] 10766.19

median(total_steps$steps)

#[1] 10765

##Histogram - Total number of steps per day

hist(total_steps$steps, main = paste("Total Steps Each Day"), col="blue", xlab="Number of Steps")

##What is the average daily activity pattern?

interval_steps <- aggregate(steps ~ interval, activity, mean)

##  Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

plot(interval_steps$interval,interval_steps$steps, type="l", xlab="Interval", ylab="Number of Steps",main="Average Number of Steps per Day by Interval")
##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?


max_steps <- interval_steps[which.max(interval_steps$steps),1]

max_steps
##[1] 835


##Imputing missing values

##Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs

nrow(activity[is.na(activity$steps),])

##[1] 2304

## New Data Set

activity2 <- transform(activity, steps = ifelse(is.na(activity$steps), interval_steps$steps[match(activity$interval, interval_steps$interval)], activity$steps))
#NAs filled in)
head(activity2)
#1 1.7169811 2012-10-01        0
#2 0.3396226 2012-10-01        5
#3 0.1320755 2012-10-01       10
#4 0.1509434 2012-10-01       15
#5 0.0754717 2012-10-01       20
#6 2.0943396 2012-10-01       25


##histogram  of the total number of steps taken each day
## Calculate and report the mean and median total number of steps taken
##per day.

steps_by_day <- aggregate(steps ~ date, activity2, sum)
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), col="blue", xlab="Number of Steps")


mean(steps_by_day$steps)

##[1] 10766.19

median(steps_by_day$steps)

##[1] 10766.19

##Calculate Differences


totaldiff <- sum(total_steps$steps) - sum(steps_by_day$steps)

mean(total_steps$steps)
#[1] 10766.19

median(total_steps$steps)
#[1] 10765

##Are there differences in activity patterns between weekdays and weekends?

##Created a plot to compare and contrast number of steps between the week and weekend. 

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
activity2$dow = as.factor(ifelse(is.element(weekdays(as.Date(activity2$date)),weekdays), "Weekday", "Weekend"))              
              
steps_by_weekday <- aggregate(steps ~ interval + dow, activity2, mean)

library(lattice)

xyplot(steps_by_weekday$steps ~ steps_by_weekday$interval|steps_by_weekday$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Steps",layout=c(1,2), type="l")
